include(sections/no-assignment.commonform)
include(sections/delegation.commonform)
include(sections/enforcement.commonform)
include(sections/law.commonform)
include(sections/litigation.commonform)
include(sections/signature.commonform)
include(sections/successors-and-assigns.commonform)
